fix: update dependency inspection to use environment variables for SDK names

diff --git a/.github/workflows/build-package.yaml b/.github/workflows/build-package.yaml
--- a/.github/workflows/build-package.yaml
+++ b/.github/workflows/build-package.yaml
@@ -1941,11 +1941,15 @@ jobs:
       - name: Inspect Dependencies Structure
         run: |
           echo "=== Library folders structure check ==="
-          ls -R ${{ github.workspace }}/libs/opus || echo "opus not found nao encontrada"
-          ls -R ${{ github.workspace }}/libs/ssl || echo "ssl not found"
-          ls -R ${{ github.workspace }}/libs/h264 || echo "h264 not found"
-          ls -R ${{ github.workspace }}/libs/bcg729 || echo "bcg729 not found"
-
+          ls -R ${{ github.workspace }}/libs/${{ env.BCG_SDK_NAME }} || echo "bcg729 not found nao encontrada"
+          ls -R ${{ github.workspace }}/libs/${{ env.H264_SDK_NAME }} || echo "h264 not found"
+          ls -R ${{ github.workspace }}/libs/${{ env.OPUS_SDK_NAME }} || echo "opus not found"
+          ls -R ${{ github.workspace }}/libs/${{ env.SSL_SDK_NAME }} || echo "ssl not found"
+        env:
+          BCG_SDK_NAME: bcg729-${{ env.BCG729_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
+          H264_SDK_NAME: h264-${{ env.OPENH264_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
+          OPUS_SDK_NAME: opus-${{ env.OPUS_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
+          SSL_SDK_NAME: ssl-${{ env.OPENSSL_VERSION }}-${{ matrix.platform }}${{ env.SDKVERSION }}-${{ matrix.arch }}.sdk
       - name: Build 
         id: build-pjsip-mac
         if: steps.cache-libs.outputs.cache-hit != 'true'
