- fix: attempt to fix nuget job by merging the nuget login and nuget package publishing steps into single one

diff --git a/.github/workflows/build-package.yaml b/.github/workflows/build-package.yaml
--- a/.github/workflows/build-package.yaml
+++ b/.github/workflows/build-package.yaml
@@ -2860,22 +2860,30 @@ jobs:
         env: 
           VERSION: ${{ env.VERSION }}
 
-      - name: NuGet login (OIDC)
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: NuGet/login@v1
-        with:
-          user: ${{ env.USERNAME }}  
-        env:
-          USERNAME: ${{ secrets.USER_NAME }}
- 
-      - name: Push to nuget.org
+      - name: Authenticate and Push to nuget.org via OIDC
         if: startsWith(github.ref, 'refs/tags/')
         run: |
+          echo "🔐 Solicitando chave temporária ao NuGet via OIDC..."
+          
+          RESPONSE=$(curl -s -X POST "https://www.nuget.org/api/v2/token" \
+            -H "Content-Type: application/json" \
+            -d "{\"owner\": \"${{ github.repository_owner }}\", \"repository\": \"${{ github.event.repository.name }}\", \"workflow\": \"${{ github.workflow }}\"}")
+          
+          API_KEY=$(echo "$RESPONSE" | grep -o '"token":"[^"]*' | grep -o '[^"]*$')
+          
+          if [ -z "$API_KEY" ]; then
+            echo "❌ Error when getting temporary nuget key. Answer:"
+            echo "$RESPONSE"
+            exit 1
+          fi
+          
+          echo "🚀 Key successfully retrieved. Starting push..."
           cd ${{ github.workspace }}/src
+          
           dotnet nuget push libpjsua2maui.${{ env.VERSION }}.nupkg \
             --source https://api.nuget.org/v3/index.json \
-            --skip-duplicate \
-            --interactive
+            --api-key "$API_KEY" \
+            --skip-duplicate
         env:
           VERSION: ${{ env.VERSION }}
 
